//instale REST Client 
//https://marketplace.visualstudio.com/items?itemName=humao.rest-client

post http://localhost:3000/messenger/webhook
content-type: application/json

{
    "phone": "11958610424",
    "text": "Olá "
}